services:
  backend:
    build: .
    volumes:
      - ./app:/code/app
    ports:
      - 80:80
    depends_on:
      - db
      
  db:
    image: postgres:15.4
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bytes
      - POSTGRES_DB=bytes
    ports:
      - 5432:5432

volumes:
  postgres:
